version: 2.1

jobs:
  build_cboard:
    machine: # executor type
      image: ubuntu-2004:202010-01
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Install node and yarn
          command: |
            sudo apt update
            sudo apt install nodejs
            sudo apt install npm
            sudo apt install yarn
      - run: 
          name: Sync cboard module 
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Install cboard
          command: |
            export NODE_OPTIONS=--max-old-space-size=8192
            cd cboard
            git checkout master 
            git pull
            yarn install
      - run:
          name: Build cboard
          command: |
            export NODE_OPTIONS=--max-old-space-size=8192
            cd cboard
            npm run build
      - persist_to_workspace:
          root: cboard
          paths:
            - build/*
  build_cordova:
    docker:
      - image: circleci/android:api-29-node
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: 
          name: Install gradle
          command: |
            wget https://services.gradle.org/distributions/gradle-6.8.1-bin.zip -P /tmp
            sudo unzip -d /opt/gradle /tmp/gradle-*.zip
            echo 'export GRADLE_HOME=/opt/gradle/gradle-6.8.1' >> $BASH_ENV
            echo 'export PATH=$PATH:/opt/gradle/gradle-6.8.1/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Cordova
          command: |
            sudo npm install -g cordova
            mkdir www
            mkdir /tmp/workspace
      - run:
          name: Install dependencias 
          command: |
            yarn install --cache-folder ~/.cache/yarn
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy Build
          command: |
            ls -a /tmp/workspace/build/
            cp -R /tmp/workspace/build/. www
            ls -a www
      - run:
          name: Build Android 
          command: |
            cordova platform add android --noresources
            cordova build android --release --verbose
            cp platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ccboard.apk
workflows:
  version: 2.1
  build_apk:
    jobs:
      - build_cboard:
          context: ccboard
          filters:
            branches:
              only: master
      - build_cordova:
          context: ccboard
          requires:
            - build_cboard
          filters:
            branches:
              only: master
